version: "3.9"

services:
  bot:
    build:
      context: .
    restart: always
    depends_on:
      - db

  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: